// Recipe data for What Should We Cook?
// Schema: { name, desc, meat, tags[], method, effort }
// tags: quick, healthy, high-protein, low-carb, comforting, kid-friendly
// method: air-fryer | oven | stovetop | grill | slow-cooker | instant-pot | no-cook
// effort: easy | medium | involved

window.MEATS = [
  { id: "chicken",     label: "Chicken",     emoji: "🍗" },
  { id: "beef",        label: "Beef",        emoji: "🥩" },
  { id: "ground-beef", label: "Ground beef", emoji: "🍔" },
  { id: "pork",        label: "Pork",        emoji: "🥓" },
  { id: "turkey",      label: "Turkey",      emoji: "🦃" },
  { id: "salmon",      label: "Salmon",      emoji: "🐟" },
  { id: "shrimp",      label: "Shrimp",      emoji: "🍤" },
  { id: "white-fish",  label: "White fish",  emoji: "🎣" },
];

window.FILTERS = [
  { id: "quick",         label: "Quick (≤30 min)" },
  { id: "healthy",       label: "Healthy" },
  { id: "high-protein",  label: "High protein" },
  { id: "low-carb",      label: "Low carb" },
  { id: "comforting",    label: "Comforting" },
  { id: "kid-friendly",  label: "Kid-friendly" },
  { id: "air-fryer",     label: "Air fryer" },
  { id: "oven",          label: "Oven" },
  { id: "stovetop",      label: "Stovetop" },
];

window.RECIPES = [
  // ================= CHICKEN =================
  { name: "Lemon Garlic Roast Chicken", desc: "Juicy whole chicken with bright lemon and herbs.", meat: "chicken", tags: ["healthy","high-protein","low-carb","comforting"], method: "oven", effort: "medium" },
  { name: "Crispy Air Fryer Chicken Thighs", desc: "Crackling skin, tender meat, almost no cleanup.", meat: "chicken", tags: ["quick","high-protein","low-carb","kid-friendly"], method: "air-fryer", effort: "easy" },
  { name: "One-Pan Chicken & Veggies", desc: "Sheet pan dinner with roasted seasonal vegetables.", meat: "chicken", tags: ["healthy","high-protein","quick"], method: "oven", effort: "easy" },
  { name: "Chicken Piccata", desc: "Pan-seared cutlets in a lemon-caper butter sauce.", meat: "chicken", tags: ["quick","high-protein","comforting"], method: "stovetop", effort: "medium" },
  { name: "Classic Chicken Parmesan", desc: "Breaded cutlets, marinara, and melty mozzarella.", meat: "chicken", tags: ["comforting","kid-friendly","high-protein"], method: "oven", effort: "medium" },
  { name: "Chicken Tikka Masala", desc: "Spiced yogurt-marinated chicken in creamy tomato sauce.", meat: "chicken", tags: ["comforting","high-protein"], method: "stovetop", effort: "involved" },
  { name: "Honey Garlic Chicken Stir-Fry", desc: "Sticky-sweet chicken with peppers and broccoli.", meat: "chicken", tags: ["quick","kid-friendly","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Greek Chicken Bowls", desc: "Marinated chicken over rice with tzatziki and cucumber.", meat: "chicken", tags: ["healthy","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Chicken Shawarma Wraps", desc: "Warmly spiced chicken in pita with garlic sauce.", meat: "chicken", tags: ["high-protein","comforting","kid-friendly"], method: "stovetop", effort: "medium" },
  { name: "Buffalo Chicken Lettuce Wraps", desc: "Spicy, crunchy, low-carb lunch or dinner.", meat: "chicken", tags: ["quick","low-carb","high-protein","healthy"], method: "stovetop", effort: "easy" },
  { name: "Creamy Tuscan Chicken", desc: "Seared chicken in sun-dried tomato cream sauce.", meat: "chicken", tags: ["comforting","low-carb","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Chicken Caesar Salad", desc: "Grilled chicken, romaine, parmesan, crunchy croutons.", meat: "chicken", tags: ["quick","high-protein","healthy"], method: "stovetop", effort: "easy" },
  { name: "Air Fryer Chicken Tenders", desc: "Kid-favorite crispy tenders with honey mustard.", meat: "chicken", tags: ["quick","kid-friendly","high-protein"], method: "air-fryer", effort: "easy" },
  { name: "Chicken Tortilla Soup", desc: "Cozy, brothy soup with lime and crispy tortillas.", meat: "chicken", tags: ["comforting","healthy"], method: "stovetop", effort: "medium" },
  { name: "Thai Basil Chicken (Pad Krapow)", desc: "Sizzling ground chicken with basil over rice.", meat: "chicken", tags: ["quick","high-protein","comforting"], method: "stovetop", effort: "easy" },
  { name: "Slow Cooker Salsa Chicken", desc: "Three ingredients, shreds for tacos or bowls.", meat: "chicken", tags: ["healthy","high-protein","kid-friendly"], method: "slow-cooker", effort: "easy" },
  { name: "Chicken Pot Pie", desc: "Flaky crust, creamy filling — pure comfort.", meat: "chicken", tags: ["comforting","kid-friendly"], method: "oven", effort: "involved" },
  { name: "Baked Pesto Chicken", desc: "Chicken breasts with pesto and melted mozzarella.", meat: "chicken", tags: ["low-carb","high-protein","quick"], method: "oven", effort: "easy" },
  { name: "Chicken Fajitas", desc: "Sizzling chicken, peppers, and onions in warm tortillas.", meat: "chicken", tags: ["kid-friendly","high-protein","quick"], method: "stovetop", effort: "easy" },
  { name: "Chicken & Dumplings", desc: "Old-fashioned soup with fluffy dumplings on top.", meat: "chicken", tags: ["comforting","kid-friendly"], method: "stovetop", effort: "involved" },
  { name: "Moroccan Chicken Tagine", desc: "Fragrant stew with olives, lemon, and warm spices.", meat: "chicken", tags: ["healthy","comforting","high-protein"], method: "stovetop", effort: "involved" },
  { name: "Chicken Caprese Skillet", desc: "Tomato, mozzarella, basil, balsamic — summer on a plate.", meat: "chicken", tags: ["low-carb","healthy","high-protein","quick"], method: "stovetop", effort: "easy" },
  { name: "Spatchcock Roast Chicken", desc: "Flattened chicken roasts faster with crisp skin.", meat: "chicken", tags: ["healthy","high-protein","low-carb"], method: "oven", effort: "medium" },
  { name: "General Tso's Chicken", desc: "Crispy chicken with sweet-spicy glaze, takeout style.", meat: "chicken", tags: ["comforting","kid-friendly"], method: "stovetop", effort: "medium" },

  // ================= BEEF =================
  { name: "Classic Beef Stew", desc: "Slow-simmered chuck with carrots and potatoes.", meat: "beef", tags: ["comforting","high-protein"], method: "stovetop", effort: "involved" },
  { name: "Garlic Butter Steak Bites", desc: "Seared cubes of sirloin in garlicky butter.", meat: "beef", tags: ["quick","low-carb","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Steakhouse Ribeye", desc: "Cast-iron ribeye with butter, garlic, and thyme.", meat: "beef", tags: ["low-carb","high-protein","comforting"], method: "stovetop", effort: "medium" },
  { name: "Beef & Broccoli Stir-Fry", desc: "Tender beef, crisp broccoli, glossy sauce.", meat: "beef", tags: ["quick","high-protein","kid-friendly"], method: "stovetop", effort: "easy" },
  { name: "Korean Bulgogi", desc: "Thin-sliced beef marinated in soy, pear, and sesame.", meat: "beef", tags: ["high-protein","comforting"], method: "stovetop", effort: "medium" },
  { name: "Pot Roast with Gravy", desc: "Fork-tender chuck roast with root vegetables.", meat: "beef", tags: ["comforting","high-protein"], method: "slow-cooker", effort: "medium" },
  { name: "Philly Cheesesteak Skillet", desc: "Thin steak, peppers, onions, provolone — no bun needed.", meat: "beef", tags: ["low-carb","high-protein","comforting","quick"], method: "stovetop", effort: "easy" },
  { name: "Beef Tacos Carne Asada", desc: "Citrus-marinated grilled steak in warm tortillas.", meat: "beef", tags: ["high-protein","kid-friendly"], method: "grill", effort: "medium" },
  { name: "Mongolian Beef", desc: "Crispy beef in a sweet-savory soy glaze.", meat: "beef", tags: ["kid-friendly","comforting","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Beef Stroganoff", desc: "Tender beef in sour cream mushroom sauce over noodles.", meat: "beef", tags: ["comforting","kid-friendly"], method: "stovetop", effort: "medium" },
  { name: "Short Rib Ragu", desc: "Slow-braised short ribs over pappardelle.", meat: "beef", tags: ["comforting","high-protein"], method: "oven", effort: "involved" },
  { name: "Thai Beef Salad", desc: "Grilled flank with lime, chili, mint, and herbs.", meat: "beef", tags: ["healthy","high-protein","low-carb"], method: "grill", effort: "medium" },
  { name: "Air Fryer Steak Bites", desc: "Quick, tender steak cubes with garlic butter.", meat: "beef", tags: ["quick","low-carb","high-protein"], method: "air-fryer", effort: "easy" },
  { name: "Beef Bourguignon", desc: "French red-wine braise with bacon and mushrooms.", meat: "beef", tags: ["comforting","high-protein"], method: "oven", effort: "involved" },
  { name: "Carne Guisada", desc: "Tex-Mex beef stew with warm spices.", meat: "beef", tags: ["comforting","high-protein"], method: "stovetop", effort: "involved" },
  { name: "Japanese Gyudon Beef Bowls", desc: "Sweet-savory simmered beef over rice with egg.", meat: "beef", tags: ["quick","comforting","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Steak Fajitas", desc: "Charred skirt steak with peppers and onions.", meat: "beef", tags: ["high-protein","kid-friendly"], method: "stovetop", effort: "medium" },
  { name: "Balsamic Marinated Flank Steak", desc: "Grilled flank sliced against the grain.", meat: "beef", tags: ["healthy","high-protein","low-carb"], method: "grill", effort: "medium" },
  { name: "Beef Pho", desc: "Aromatic broth, rice noodles, and thin-sliced beef.", meat: "beef", tags: ["comforting","healthy"], method: "stovetop", effort: "involved" },
  { name: "Chipotle-Style Barbacoa", desc: "Shredded, smoky, saucy beef for bowls or tacos.", meat: "beef", tags: ["high-protein","comforting"], method: "slow-cooker", effort: "medium" },
  { name: "Steak Salad with Blue Cheese", desc: "Pan-seared steak over greens with tangy dressing.", meat: "beef", tags: ["healthy","low-carb","high-protein","quick"], method: "stovetop", effort: "easy" },
  { name: "Beef Shawarma Plate", desc: "Spiced shaved beef with garlic sauce and pickles.", meat: "beef", tags: ["high-protein","comforting"], method: "stovetop", effort: "medium" },

  // ================= GROUND BEEF =================
  { name: "Classic Cheeseburgers", desc: "Juicy smash-style burgers with melty cheese.", meat: "ground-beef", tags: ["quick","kid-friendly","comforting","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Weeknight Spaghetti Bolognese", desc: "Rich meat sauce over spaghetti.", meat: "ground-beef", tags: ["kid-friendly","comforting"], method: "stovetop", effort: "medium" },
  { name: "Taco Tuesday Skillet", desc: "Seasoned beef, shells, lettuce, cheese, salsa.", meat: "ground-beef", tags: ["quick","kid-friendly","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Meatloaf with Glaze", desc: "Tender loaf with tangy ketchup-brown sugar top.", meat: "ground-beef", tags: ["comforting","kid-friendly"], method: "oven", effort: "medium" },
  { name: "Stuffed Bell Peppers", desc: "Peppers filled with beef, rice, and tomato.", meat: "ground-beef", tags: ["comforting","healthy","high-protein"], method: "oven", effort: "medium" },
  { name: "Cheeseburger Bowls", desc: "All the burger flavor over greens, no bun.", meat: "ground-beef", tags: ["low-carb","quick","high-protein","healthy"], method: "stovetop", effort: "easy" },
  { name: "Chili con Carne", desc: "Hearty beef chili with beans and warm spices.", meat: "ground-beef", tags: ["comforting","high-protein","kid-friendly"], method: "stovetop", effort: "medium" },
  { name: "Lasagna", desc: "Layers of meat sauce, ricotta, and cheese.", meat: "ground-beef", tags: ["comforting","kid-friendly"], method: "oven", effort: "involved" },
  { name: "Sloppy Joes", desc: "Tangy, sweet beef on toasted buns.", meat: "ground-beef", tags: ["quick","kid-friendly","comforting"], method: "stovetop", effort: "easy" },
  { name: "Shepherd's Pie", desc: "Savory beef under fluffy mashed potatoes.", meat: "ground-beef", tags: ["comforting","kid-friendly"], method: "oven", effort: "involved" },
  { name: "Korean Beef Bowls", desc: "20-minute sweet-savory beef over rice.", meat: "ground-beef", tags: ["quick","kid-friendly","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Swedish Meatballs", desc: "Tender meatballs in creamy gravy over noodles.", meat: "ground-beef", tags: ["comforting","kid-friendly"], method: "stovetop", effort: "medium" },
  { name: "Air Fryer Meatballs", desc: "Easy Italian meatballs — great for pasta or subs.", meat: "ground-beef", tags: ["quick","kid-friendly","high-protein"], method: "air-fryer", effort: "easy" },
  { name: "Picadillo", desc: "Cuban-style ground beef with olives and raisins.", meat: "ground-beef", tags: ["comforting","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Beefy Baked Ziti", desc: "Cheesy pasta bake the kids always finish.", meat: "ground-beef", tags: ["comforting","kid-friendly"], method: "oven", effort: "medium" },
  { name: "Greek Beef Gyros", desc: "Spiced beef wraps with tzatziki and tomato.", meat: "ground-beef", tags: ["high-protein","kid-friendly"], method: "stovetop", effort: "medium" },
  { name: "Zucchini Boats", desc: "Hollowed zucchini stuffed with seasoned beef and cheese.", meat: "ground-beef", tags: ["low-carb","healthy","high-protein"], method: "oven", effort: "medium" },
  { name: "Salisbury Steak", desc: "Seasoned beef patties in mushroom gravy.", meat: "ground-beef", tags: ["comforting","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Beef Empanadas", desc: "Flaky hand pies with savory beef filling.", meat: "ground-beef", tags: ["kid-friendly","comforting"], method: "oven", effort: "involved" },
  { name: "American Goulash", desc: "One-pot elbows with beef, tomato, and cheese.", meat: "ground-beef", tags: ["comforting","kid-friendly"], method: "stovetop", effort: "easy" },
  { name: "Taco Lettuce Cups", desc: "All taco flavor, low-carb, crisp and fresh.", meat: "ground-beef", tags: ["low-carb","healthy","high-protein","quick"], method: "stovetop", effort: "easy" },
  { name: "Cottage Pie", desc: "Classic British beef & potato bake.", meat: "ground-beef", tags: ["comforting","kid-friendly"], method: "oven", effort: "involved" },

  // ================= PORK =================
  { name: "Slow Cooker Pulled Pork", desc: "Fall-apart pork shoulder for sandwiches and bowls.", meat: "pork", tags: ["comforting","high-protein","kid-friendly"], method: "slow-cooker", effort: "easy" },
  { name: "Honey Garlic Pork Chops", desc: "Pan-seared chops with sticky glaze.", meat: "pork", tags: ["quick","kid-friendly","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Herb-Crusted Pork Tenderloin", desc: "Roasted tenderloin with Dijon and rosemary.", meat: "pork", tags: ["healthy","low-carb","high-protein"], method: "oven", effort: "medium" },
  { name: "Air Fryer Pork Chops", desc: "Crispy outside, juicy inside, 15 minutes flat.", meat: "pork", tags: ["quick","low-carb","high-protein"], method: "air-fryer", effort: "easy" },
  { name: "Carnitas Tacos", desc: "Crispy-edged braised pork with lime and cilantro.", meat: "pork", tags: ["comforting","high-protein","kid-friendly"], method: "slow-cooker", effort: "medium" },
  { name: "Sweet & Sour Pork", desc: "Crispy pork with pineapple and peppers.", meat: "pork", tags: ["kid-friendly","comforting"], method: "stovetop", effort: "medium" },
  { name: "Maple Dijon Pork Tenderloin", desc: "Sweet-tangy glaze with a perfect sear.", meat: "pork", tags: ["healthy","high-protein","quick"], method: "oven", effort: "easy" },
  { name: "Pork Banh Mi Bowls", desc: "Vietnamese pork over rice with pickled veg.", meat: "pork", tags: ["healthy","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Cuban Mojo Pork", desc: "Citrus-garlic marinated pork, roasted to tender.", meat: "pork", tags: ["high-protein","comforting"], method: "oven", effort: "involved" },
  { name: "Pork Fried Rice", desc: "Leftover pork + day-old rice = weeknight win.", meat: "pork", tags: ["quick","kid-friendly","comforting"], method: "stovetop", effort: "easy" },
  { name: "Smothered Pork Chops", desc: "Southern chops in creamy onion gravy.", meat: "pork", tags: ["comforting","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Pork Schnitzel", desc: "Thin, crispy, golden cutlets with lemon.", meat: "pork", tags: ["comforting","kid-friendly","high-protein"], method: "stovetop", effort: "medium" },
  { name: "BBQ Pork Ribs", desc: "Oven low-and-slow then finished with sauce.", meat: "pork", tags: ["comforting","high-protein"], method: "oven", effort: "involved" },
  { name: "Italian Sausage & Peppers", desc: "Rustic skillet perfect on a hoagie.", meat: "pork", tags: ["comforting","kid-friendly"], method: "stovetop", effort: "easy" },
  { name: "Pork Larb", desc: "Thai ground pork salad, bright and herby.", meat: "pork", tags: ["healthy","low-carb","high-protein","quick"], method: "stovetop", effort: "easy" },
  { name: "Char Siu Pork", desc: "Chinese BBQ pork with sweet lacquered glaze.", meat: "pork", tags: ["comforting","high-protein"], method: "oven", effort: "medium" },
  { name: "Pork Milanese", desc: "Pounded, breaded cutlet with arugula salad.", meat: "pork", tags: ["quick","kid-friendly","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Apple-Stuffed Pork Loin", desc: "Roast pork with sweet apple-herb stuffing.", meat: "pork", tags: ["comforting","high-protein"], method: "oven", effort: "involved" },
  { name: "Pork Posole", desc: "Mexican hominy stew with tender pork shoulder.", meat: "pork", tags: ["comforting","healthy","high-protein"], method: "stovetop", effort: "involved" },
  { name: "Breakfast-for-Dinner Bacon Hash", desc: "Crispy potatoes, bacon, eggs — everyone loves it.", meat: "pork", tags: ["comforting","kid-friendly","quick"], method: "stovetop", effort: "easy" },
  { name: "Sausage & White Bean Soup", desc: "Quick hearty soup with kale and garlic.", meat: "pork", tags: ["healthy","comforting","quick"], method: "stovetop", effort: "easy" },
  { name: "Air Fryer Bratwurst", desc: "Juicy brats ready in under 15 minutes.", meat: "pork", tags: ["quick","kid-friendly","high-protein"], method: "air-fryer", effort: "easy" },

  // ================= TURKEY =================
  { name: "Ground Turkey Taco Skillet", desc: "Lean, quick, family-friendly taco night.", meat: "turkey", tags: ["quick","healthy","high-protein","kid-friendly"], method: "stovetop", effort: "easy" },
  { name: "Turkey Meatballs in Marinara", desc: "Tender meatballs over pasta or zucchini noodles.", meat: "turkey", tags: ["healthy","high-protein","kid-friendly"], method: "stovetop", effort: "medium" },
  { name: "Turkey Chili", desc: "Lighter take on classic chili, just as cozy.", meat: "turkey", tags: ["healthy","comforting","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Turkey & Spinach Stuffed Shells", desc: "Jumbo shells with ricotta and lean turkey.", meat: "turkey", tags: ["comforting","kid-friendly","high-protein"], method: "oven", effort: "involved" },
  { name: "Air Fryer Turkey Meatballs", desc: "Juicy and perfectly browned in 12 minutes.", meat: "turkey", tags: ["quick","healthy","high-protein","kid-friendly"], method: "air-fryer", effort: "easy" },
  { name: "Turkey Lettuce Wraps", desc: "Asian-style turkey with water chestnuts and hoisin.", meat: "turkey", tags: ["quick","healthy","low-carb","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Herb-Roasted Turkey Breast", desc: "Juicy roasted breast with rosemary and thyme.", meat: "turkey", tags: ["healthy","high-protein","low-carb"], method: "oven", effort: "medium" },
  { name: "Turkey Burgers with Avocado", desc: "Lean patties with creamy avocado mayo.", meat: "turkey", tags: ["healthy","high-protein","quick"], method: "stovetop", effort: "easy" },
  { name: "Turkey Bolognese", desc: "A lighter, still-rich version of the classic.", meat: "turkey", tags: ["healthy","comforting","kid-friendly"], method: "stovetop", effort: "medium" },
  { name: "Turkey Zucchini Boats", desc: "Baked zucchini stuffed with seasoned turkey.", meat: "turkey", tags: ["low-carb","healthy","high-protein"], method: "oven", effort: "medium" },
  { name: "Turkey Pot Pie", desc: "Great for leftovers, flaky and cozy.", meat: "turkey", tags: ["comforting","kid-friendly"], method: "oven", effort: "involved" },
  { name: "Turkey & Rice Stuffed Peppers", desc: "Classic stuffed peppers gone lighter.", meat: "turkey", tags: ["healthy","high-protein","comforting"], method: "oven", effort: "medium" },
  { name: "Turkey Sausage Breakfast Hash", desc: "Sweet potato, peppers, turkey sausage — any meal.", meat: "turkey", tags: ["healthy","high-protein","quick"], method: "stovetop", effort: "easy" },
  { name: "Greek Turkey Meatballs", desc: "Feta, oregano, lemon — serve with tzatziki.", meat: "turkey", tags: ["healthy","high-protein","low-carb"], method: "oven", effort: "medium" },
  { name: "Turkey Tetrazzini", desc: "Creamy, cheesy pasta bake, leftover hero.", meat: "turkey", tags: ["comforting","kid-friendly"], method: "oven", effort: "medium" },
  { name: "Thai Turkey Basil Stir-Fry", desc: "Fast, fragrant, and family-adjustable heat.", meat: "turkey", tags: ["quick","healthy","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Turkey Shepherd's Pie", desc: "Lean twist on the British classic.", meat: "turkey", tags: ["comforting","kid-friendly","healthy"], method: "oven", effort: "involved" },
  { name: "Turkey Taco Lettuce Wraps", desc: "Low-carb, high-protein, fast weeknight dinner.", meat: "turkey", tags: ["quick","low-carb","healthy","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Turkey Meatball Soup", desc: "Mini meatballs with orzo and greens.", meat: "turkey", tags: ["comforting","healthy","kid-friendly"], method: "stovetop", effort: "medium" },
  { name: "Buffalo Turkey Burgers", desc: "Spicy-tangy with blue cheese and crunchy slaw.", meat: "turkey", tags: ["high-protein","quick","healthy"], method: "stovetop", effort: "easy" },
  { name: "Moroccan Turkey Skillet", desc: "Spiced turkey with chickpeas and apricots.", meat: "turkey", tags: ["healthy","high-protein","comforting"], method: "stovetop", effort: "medium" },
  { name: "Turkey Cobb Salad", desc: "Leftover turkey, egg, bacon, blue cheese.", meat: "turkey", tags: ["low-carb","healthy","high-protein","quick"], method: "no-cook", effort: "easy" },

  // ================= SALMON =================
  { name: "Honey Garlic Glazed Salmon", desc: "Sweet-savory glaze in under 20 minutes.", meat: "salmon", tags: ["quick","healthy","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Air Fryer Salmon", desc: "Flaky, perfect fillets in 10 minutes.", meat: "salmon", tags: ["quick","healthy","high-protein","low-carb"], method: "air-fryer", effort: "easy" },
  { name: "Lemon Herb Baked Salmon", desc: "Sheet-pan simple with asparagus.", meat: "salmon", tags: ["quick","healthy","low-carb","high-protein"], method: "oven", effort: "easy" },
  { name: "Miso Glazed Salmon", desc: "Umami-rich glaze with a hint of sweetness.", meat: "salmon", tags: ["healthy","high-protein","low-carb"], method: "oven", effort: "easy" },
  { name: "Teriyaki Salmon Bowls", desc: "Salmon over rice with edamame and cucumber.", meat: "salmon", tags: ["healthy","high-protein","kid-friendly"], method: "stovetop", effort: "medium" },
  { name: "Salmon Piccata", desc: "Lemon-caper butter sauce, bright and quick.", meat: "salmon", tags: ["quick","low-carb","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Blackened Salmon Tacos", desc: "Spiced salmon with slaw and lime crema.", meat: "salmon", tags: ["healthy","high-protein","quick"], method: "stovetop", effort: "medium" },
  { name: "Salmon Caesar Salad", desc: "Pan-seared salmon over crisp romaine.", meat: "salmon", tags: ["low-carb","healthy","high-protein","quick"], method: "stovetop", effort: "easy" },
  { name: "Maple Dijon Salmon", desc: "Sticky, tangy, weeknight-easy.", meat: "salmon", tags: ["quick","healthy","high-protein"], method: "oven", effort: "easy" },
  { name: "Salmon Rice Bowls (Bibimbap-style)", desc: "Salmon, rice, veggies, spicy mayo.", meat: "salmon", tags: ["healthy","high-protein","kid-friendly"], method: "stovetop", effort: "medium" },
  { name: "Pan-Seared Salmon with Lemon Butter", desc: "Crispy skin, silky inside, 15 min total.", meat: "salmon", tags: ["quick","low-carb","high-protein","healthy"], method: "stovetop", effort: "easy" },
  { name: "Salmon Chowder", desc: "Cozy, creamy soup with potatoes and dill.", meat: "salmon", tags: ["comforting","healthy"], method: "stovetop", effort: "medium" },
  { name: "Mediterranean Salmon", desc: "Olives, tomatoes, capers, feta — bright and easy.", meat: "salmon", tags: ["healthy","low-carb","high-protein"], method: "oven", effort: "easy" },
  { name: "Salmon Patties", desc: "Crispy, budget-friendly, kid-approved.", meat: "salmon", tags: ["quick","kid-friendly","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Bagel Lox Board", desc: "Cold-smoked salmon, bagels, capers, cream cheese.", meat: "salmon", tags: ["quick","healthy"], method: "no-cook", effort: "easy" },
  { name: "Ginger Soy Salmon", desc: "Marinated and broiled, weeknight-fast.", meat: "salmon", tags: ["quick","healthy","high-protein","low-carb"], method: "oven", effort: "easy" },
  { name: "Salmon with Dill Yogurt", desc: "Baked salmon with cool herby sauce.", meat: "salmon", tags: ["healthy","high-protein","low-carb"], method: "oven", effort: "easy" },
  { name: "Furikake Salmon", desc: "Hawaiian-style with mayo and rice seasoning.", meat: "salmon", tags: ["quick","kid-friendly","high-protein"], method: "oven", effort: "easy" },
  { name: "Salmon Niçoise Salad", desc: "French classic with seared salmon, egg, green beans.", meat: "salmon", tags: ["healthy","low-carb","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Sheet Pan Salmon & Veggies", desc: "Everything on one tray — easiest cleanup.", meat: "salmon", tags: ["quick","healthy","high-protein"], method: "oven", effort: "easy" },
  { name: "Salmon Poke Bowls", desc: "Cubed raw salmon, rice, edamame, avocado.", meat: "salmon", tags: ["healthy","high-protein"], method: "no-cook", effort: "medium" },
  { name: "Cajun Salmon Alfredo", desc: "Spicy salmon over creamy fettuccine.", meat: "salmon", tags: ["comforting","high-protein"], method: "stovetop", effort: "medium" },

  // ================= SHRIMP =================
  { name: "Garlic Butter Shrimp", desc: "Ready in 10 minutes, wildly flavorful.", meat: "shrimp", tags: ["quick","low-carb","high-protein","healthy"], method: "stovetop", effort: "easy" },
  { name: "Shrimp Scampi Linguine", desc: "Garlicky white wine shrimp over pasta.", meat: "shrimp", tags: ["quick","comforting","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Air Fryer Coconut Shrimp", desc: "Crunchy, sweet, perfect for dipping.", meat: "shrimp", tags: ["quick","kid-friendly","high-protein"], method: "air-fryer", effort: "easy" },
  { name: "Shrimp Tacos with Slaw", desc: "Quick spiced shrimp with crunchy cabbage.", meat: "shrimp", tags: ["quick","healthy","high-protein","kid-friendly"], method: "stovetop", effort: "easy" },
  { name: "Cajun Shrimp Pasta", desc: "Spicy creamy sauce over fettuccine.", meat: "shrimp", tags: ["comforting","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Honey Garlic Shrimp Stir-Fry", desc: "Sticky-sweet shrimp with veggies and rice.", meat: "shrimp", tags: ["quick","kid-friendly","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Shrimp Fried Rice", desc: "Takeout at home in under 20 minutes.", meat: "shrimp", tags: ["quick","comforting","kid-friendly"], method: "stovetop", effort: "easy" },
  { name: "Shrimp Ceviche", desc: "Bright citrus-marinated shrimp with avocado.", meat: "shrimp", tags: ["healthy","low-carb","high-protein"], method: "no-cook", effort: "easy" },
  { name: "Bang Bang Shrimp", desc: "Crispy shrimp with creamy sweet-spicy sauce.", meat: "shrimp", tags: ["comforting","kid-friendly","high-protein"], method: "air-fryer", effort: "medium" },
  { name: "Shrimp Boil Foil Packs", desc: "Shrimp, sausage, corn, potatoes — party in a pouch.", meat: "shrimp", tags: ["comforting","high-protein"], method: "oven", effort: "medium" },
  { name: "Lemon Pepper Shrimp", desc: "Zesty, simple, on the table fast.", meat: "shrimp", tags: ["quick","healthy","low-carb","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Shrimp & Grits", desc: "Cajun-spiced shrimp over creamy cheese grits.", meat: "shrimp", tags: ["comforting","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Thai Shrimp Curry", desc: "Red curry coconut with shrimp and peppers.", meat: "shrimp", tags: ["comforting","high-protein","healthy"], method: "stovetop", effort: "medium" },
  { name: "Shrimp Pad Thai", desc: "Rice noodles tossed with tamarind-peanut sauce.", meat: "shrimp", tags: ["comforting","kid-friendly"], method: "stovetop", effort: "medium" },
  { name: "Shrimp Quesadillas", desc: "Cheesy, crisp, dinner in 15 minutes.", meat: "shrimp", tags: ["quick","kid-friendly","comforting"], method: "stovetop", effort: "easy" },
  { name: "Shrimp Caesar Salad", desc: "Pan-seared shrimp on crisp romaine.", meat: "shrimp", tags: ["quick","low-carb","healthy","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Garlic Shrimp Zucchini Noodles", desc: "Low-carb, bright, and satisfying.", meat: "shrimp", tags: ["low-carb","healthy","high-protein","quick"], method: "stovetop", effort: "easy" },
  { name: "Shrimp Étouffée", desc: "Louisiana-style stew over rice.", meat: "shrimp", tags: ["comforting","high-protein"], method: "stovetop", effort: "involved" },
  { name: "Sheet Pan Shrimp Fajitas", desc: "Everything roasts together — minimal dishes.", meat: "shrimp", tags: ["quick","healthy","high-protein"], method: "oven", effort: "easy" },
  { name: "Shrimp Spring Rolls", desc: "Fresh rice-paper rolls with peanut dip.", meat: "shrimp", tags: ["healthy","quick","high-protein"], method: "no-cook", effort: "medium" },
  { name: "Shrimp Tikka Masala", desc: "Creamy tomato curry, ready in 25 minutes.", meat: "shrimp", tags: ["comforting","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Garlicky Shrimp Skewers", desc: "Quick grilled skewers with lemon.", meat: "shrimp", tags: ["quick","healthy","low-carb","high-protein"], method: "grill", effort: "easy" },

  // ================= WHITE FISH =================
  { name: "Crispy Fish Tacos", desc: "Golden battered fish with slaw and lime crema.", meat: "white-fish", tags: ["comforting","kid-friendly"], method: "stovetop", effort: "medium" },
  { name: "Lemon Butter Cod", desc: "Flaky cod in bright lemon-butter sauce.", meat: "white-fish", tags: ["quick","healthy","low-carb","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Air Fryer Fish & Chips", desc: "Crunchy cod with lighter oven fries.", meat: "white-fish", tags: ["kid-friendly","comforting","high-protein"], method: "air-fryer", effort: "medium" },
  { name: "Baked Parmesan Tilapia", desc: "Crispy cheesy crust, quick weeknight dinner.", meat: "white-fish", tags: ["quick","kid-friendly","high-protein","low-carb"], method: "oven", effort: "easy" },
  { name: "Fish Piccata", desc: "Lemon-caper sauce over pan-seared fillets.", meat: "white-fish", tags: ["quick","healthy","low-carb","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Thai Coconut Fish Curry", desc: "Fragrant coconut broth with gentle heat.", meat: "white-fish", tags: ["comforting","healthy","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Miso Butter Cod", desc: "Umami-rich, buttery, almost no effort.", meat: "white-fish", tags: ["healthy","low-carb","high-protein"], method: "oven", effort: "easy" },
  { name: "Fish en Papillote", desc: "Fish steamed in parchment with herbs and veg.", meat: "white-fish", tags: ["healthy","low-carb","high-protein"], method: "oven", effort: "medium" },
  { name: "Classic Fish Fingers", desc: "Homemade, crunchy, kid-approved forever.", meat: "white-fish", tags: ["kid-friendly","comforting","high-protein"], method: "oven", effort: "easy" },
  { name: "Blackened Cod Bowls", desc: "Spiced cod over rice with avocado and mango.", meat: "white-fish", tags: ["healthy","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Halibut with Brown Butter", desc: "Seared halibut with nutty butter and lemon.", meat: "white-fish", tags: ["quick","low-carb","high-protein","healthy"], method: "stovetop", effort: "easy" },
  { name: "Fish Chowder", desc: "Creamy potato-fish soup with chives.", meat: "white-fish", tags: ["comforting","healthy"], method: "stovetop", effort: "medium" },
  { name: "Mediterranean Baked Sea Bass", desc: "Tomatoes, olives, capers, herbs.", meat: "white-fish", tags: ["healthy","low-carb","high-protein"], method: "oven", effort: "medium" },
  { name: "Fish Cakes", desc: "Pan-fried cakes with lemon aioli.", meat: "white-fish", tags: ["comforting","kid-friendly","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Beer Battered Fish Sandwich", desc: "Crunchy fish with tartar sauce on a soft bun.", meat: "white-fish", tags: ["comforting","kid-friendly"], method: "stovetop", effort: "medium" },
  { name: "Garlic Ginger Steamed Fish", desc: "Cantonese-style steamed fish with scallion oil.", meat: "white-fish", tags: ["healthy","low-carb","high-protein","quick"], method: "stovetop", effort: "easy" },
  { name: "Cajun Cod Skillet", desc: "Spicy one-pan cod with peppers and rice.", meat: "white-fish", tags: ["quick","healthy","high-protein"], method: "stovetop", effort: "easy" },
  { name: "Fish Veracruz", desc: "Mexican fish with tomato, olives, capers.", meat: "white-fish", tags: ["healthy","low-carb","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Panko-Crusted Tilapia", desc: "Crunchy golden crust, flaky inside.", meat: "white-fish", tags: ["quick","kid-friendly","high-protein"], method: "oven", effort: "easy" },
  { name: "Coconut Curry Fish Stew", desc: "Caribbean-inspired, warm and cozy.", meat: "white-fish", tags: ["comforting","healthy","high-protein"], method: "stovetop", effort: "medium" },
  { name: "Sheet Pan Lemon Cod & Potatoes", desc: "Complete dinner on one pan in 25 minutes.", meat: "white-fish", tags: ["quick","healthy","high-protein"], method: "oven", effort: "easy" },
  { name: "Fish Tostadas", desc: "Crispy tortillas with flaky fish and slaw.", meat: "white-fish", tags: ["healthy","high-protein","quick"], method: "stovetop", effort: "medium" },
];
